"""Site-wide settings shared by the build scripts."""

# The address search engines should treat as the real site (canonicals, sitemap,
# robots.txt, Open Graph, structured data). Deploy this only once the domain
# points at Vercel. Also change mudra_site in the Shopify redirect theme
# (snippets/mudra-redirect.liquid). Then run:
#   python3 scripts/build_pages.py && python3 scripts/fingerprint.py
# HELD (8 Oct 2026): wearmudra.in has no DNS yet. Switch to "https://wearmudra.in"
# only when it serves this site.
SITE_URL = "https://mudraclothing-co.vercel.app"

# Names. BRAND in the logo, page titles and running copy; LEGAL_NAME in the
# footer copyright, legal pages, business details and the Organization schema.
BRAND = "Mudra"
LEGAL_NAME = "Mudra Clothing Company"
SITE_NAME = LEGAL_NAME   # kept for older imports

# Customer email. Every page gets it from here ({{email}} in _src/pages).
# HELD (8 Oct 2026): hello@wearmudra.in doesn't receive mail yet, so the working
# Gmail stays. To switch: set "hello@wearmudra.in" and MAILBOX_LIVE = False, rebuild,
# send a test email, then MAILBOX_LIVE = True and rebuild again.
CONTACT_EMAIL = "abhijeet.designmail@gmail.com"
# False until the mailbox exists and receives mail: the address is then marked
# as a placeholder (.tbd, highlighted with body.review). Flip to True once a
# test email to it arrives, then rebuild.
MAILBOX_LIVE = True   # the Gmail above works

INSTAGRAM_HANDLE = "@wearmudra"
INSTAGRAM_URL = "https://instagram.com/wearmudra"

# Default share image (1200x630), generated by build_seo.py if missing.
OG_IMAGE = "/assets/img/og/mudra-og-face-card.jpg"

# Pre-order arrival window, calendar days from order to door.
# MUST match ORDERING.minDays / ORDERING.maxDays in assets/js/shop.js
# (the mode itself, 'preorder' or 'instock', is read from shop.js).
PREORDER_MIN_DAYS = 7
PREORDER_MAX_DAYS = 10
