"""Site-wide settings shared by the build scripts."""

# The address search engines should treat as the real site (canonicals, sitemap,
# robots.txt, Open Graph, structured data). Deploy this only once the domain
# points at Vercel. Also change mudra_site in the Shopify redirect theme
# (snippets/mudra-redirect.liquid). Then run:
#   python3 scripts/build_pages.py && python3 scripts/fingerprint.py
# 8 Oct 2026: wearmudra.shop is live on Vercel. The bare domain 308-redirects to www,
# so www is the canonical address. If Vercel is set the other way round, follow it.
# (mudraclothing-co.vercel.app keeps working; wearmudra.in was never registered.)
SITE_URL = "https://www.wearmudra.shop"

# Names. BRAND in the logo, page titles and running copy; LEGAL_NAME in the
# footer copyright, legal pages, business details and the Organization schema.
BRAND = "Mudra"
LEGAL_NAME = "Mudra Clothing Company"
SITE_NAME = LEGAL_NAME   # kept for older imports

# Customer email. Every page gets it from here ({{email}} in _src/pages).
# HELD (8 Oct 2026): hello@wearmudra.in doesn't receive mail yet, so the working
# Gmail stays. To switch: set "hello@wearmudra.in" and MAILBOX_LIVE = False, rebuild,
# send a test email, then MAILBOX_LIVE = True and rebuild again.
CONTACT_EMAIL = "abhijeet.designmail@gmail.com"
# False until the mailbox exists and receives mail: the address is then marked
# as a placeholder (.tbd, highlighted with body.review). Flip to True once a
# test email to it arrives, then rebuild.
MAILBOX_LIVE = True   # the Gmail above works

INSTAGRAM_HANDLE = "@wear.mudra"
INSTAGRAM_URL = "https://www.instagram.com/wear.mudra/"

# Default share image (1200x630), generated by build_seo.py if missing.
OG_IMAGE = "/assets/img/og/mudra-og-face-card.jpg"

# Pre-order arrival window, calendar days from order to door.
# MUST match ORDERING.minDays / ORDERING.maxDays in assets/js/shop.js
# (the mode itself, 'preorder' or 'instock', is read from shop.js).
PREORDER_MIN_DAYS = 7
PREORDER_MAX_DAYS = 10

# Google Merchant feed (feeds/google-merchant.xml): who the tees are for.
FEED_GENDER = "unisex"      # male | female | unisex
FEED_AGE_GROUP = "adult"
