"""Site-wide settings shared by the build scripts."""

# The address search engines should treat as the real site.
# wearmudra.in doesn't resolve yet (no DNS). Pointing canonicals at it now
# would tell Google to drop the only working site. When the domain is live
# on Vercel, change this one line, then run:
#   python3 scripts/build_pages.py && python3 scripts/fingerprint.py
SITE_URL = "https://mudraclothing-co.vercel.app"

SITE_NAME = "Mudra Studios"
CONTACT_EMAIL = "abhijeet.designmail@gmail.com"

# Add the handle once it exists; it goes into the Organization structured data.
INSTAGRAM_URL = ""   # e.g. "https://www.instagram.com/<handle>/"

# Default share image (1200x630), generated by build_seo.py if missing.
OG_IMAGE = "/assets/img/og/mudra-og.jpg"

# Pre-order arrival window, calendar days from order to door.
# MUST match ORDERING.minDays / ORDERING.maxDays in assets/js/shop.js
# (the mode itself, 'preorder' or 'instock', is read from shop.js).
PREORDER_MIN_DAYS = 7
PREORDER_MAX_DAYS = 10
